- name: Install KL root CA
  notify: update ca trust
  copy:
    src: files/kasperskylabsrootca.cer
    dest: /etc/pki/ca-trust/source/anchors

- name: Install KL Global CA G2
  notify: update ca trust
  copy:
    src: files/KasperskyLabGlobalCAG2.cer
    dest: /etc/pki/ca-trust/source/anchors

#  - name: Enable CNTLM on startup
#    systemd:
#      name: cntlm.service
#      state: started
#      enabled: yes
